#+author: conao3
#+date: <2018-10-25 Thu>

[[https://github.com/conao3/docker-po4a][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/docker-po4a.png]]
[[https://github.com/conao3/docker-po4a/blob/master/LICENSE][https://img.shields.io/github/license/conao3/docker-po4a.svg?style=flat-square]]
[[https://github.com/conao3/docker-po4a/releases][https://img.shields.io/github/tag/conao3/docker-po4a.svg?style=flat-square]]
[[https://www.patreon.com/conao3][https://img.shields.io/badge/patreon-become%20a%20patron-orange.svg?logo=patreon&style=flat-square]]
[[https://twitter.com/conao_3][https://img.shields.io/badge/twitter-@conao__3-blue.svg?logo=twitter&style=flat-square]]
[[https://conao3-support.slack.com/join/shared_invite/zt-33xfnokp-XuDHuhsF~9LazchJdep9ow#/shared-invite/email][https://img.shields.io/badge/chat-on_slack-blue.svg?logo=slack&style=flat-square]]

* Table of Contents
- [[#description][Description]]
- [[#install][Install]]
- [[#usage][Usage]]
- [[#information][Information]]

* Description
A standalone Docker image for [[https://github.com/mquinson/po4a][po4a]], the PO for anything tool that simplifies documentation translation using gettext.

This image lets you run po4a without installing Perl dependencies on your system.

* Install
Make sure Docker is installed on your system.

#+begin_src bash
# macOS
brew install docker
brew cask install docker

# Verify installation
docker version
#+end_src

* Usage
** Basic Usage
Run po4a directly from the Docker image:

#+begin_src bash
docker container run -i --rm conao3/po4a:0.55 --version
#+end_src

For convenience, create an alias:

#+begin_src bash
alias po4a='docker container run -i --rm conao3/po4a:0.55'
po4a --version
#+end_src

** Using Other po4a Tools
The default entrypoint is ~po4a~. To use other bundled tools like ~po4a-translate~, override the entrypoint:

#+begin_src bash
docker container run -i --rm --entrypoint="" conao3/po4a:0.55 po4a-translate --version
#+end_src

You can set up aliases for all the bundled tools:

#+begin_src bash
alias po4a='docker container run -i --rm conao3/po4a:0.55'
alias po4a-gettextize='docker container run -i --rm --entrypoint="" conao3/po4a:0.55 po4a-gettextize'
alias po4a-normalize='docker container run -i --rm --entrypoint="" conao3/po4a:0.55 po4a-normalize'
alias po4a-translate='docker container run -i --rm --entrypoint="" conao3/po4a:0.55 po4a-translate'
alias po4a-updatepo='docker container run -i --rm --entrypoint="" conao3/po4a:0.55 po4a-updatepo'
#+end_src

* Information
** Support
If you find this project useful, consider supporting its development:

[[https://www.patreon.com/conao3][https://c5.patreon.com/external/logo/become_a_patron_button.png]]

** Community
Feedback and suggestions are always welcome.

- Open an issue on [[https://github.com/conao3/docker-po4a/issues][GitHub Issues]]
- Join the conversation on [[https://conao3-support.slack.com/join/shared_invite/zt-33xfnokp-XuDHuhsF~9LazchJdep9ow#/shared-invite/email][Slack]]

** Contributing
Pull requests are welcome. Feel free to contribute improvements or fixes.

** License
#+begin_example
Affero General Public License Version 3 (AGPLv3)
Copyright (c) Naoya Yamashita - https://conao3.com
https://github.com/conao3/docker-po4a/blob/master/LICENSE
#+end_example

** Author
Naoya Yamashita ([[https://github.com/conao3][conao3]])
